"""add_vision_board_table

Revision ID: dcd8e9331b03
Revises: f396d99fa892
Create Date: 2025-07-26 19:02:50.714883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd8e9331b03'
down_revision: Union[str, Sequence[str], None] = 'f396d99fa892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vision_items_category'), table_name='vision_items')
    op.drop_index(op.f('ix_vision_items_id'), table_name='vision_items')
    op.drop_index(op.f('ix_vision_items_is_completed'), table_name='vision_items')
    op.drop_index(op.f('ix_vision_items_title'), table_name='vision_items')
    op.drop_index(op.f('ix_vision_items_user_id'), table_name='vision_items')
    op.drop_table('vision_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_date', sa.DATETIME(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_items_user_id'), 'vision_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_vision_items_title'), 'vision_items', ['title'], unique=False)
    op.create_index(op.f('ix_vision_items_is_completed'), 'vision_items', ['is_completed'], unique=False)
    op.create_index(op.f('ix_vision_items_id'), 'vision_items', ['id'], unique=False)
    op.create_index(op.f('ix_vision_items_category'), 'vision_items', ['category'], unique=False)
    # ### end Alembic commands ###
