"""Add crawled content fields to rss_articles

Revision ID: f396d99fa892
Revises: 
Create Date: 2025-07-26 14:59:46.296585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f396d99fa892'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_articles', sa.Column('crawled_content', sa.Text(), nullable=True))
    op.add_column('rss_articles', sa.Column('crawled_html', sa.Text(), nullable=True))
    op.add_column('rss_articles', sa.Column('crawled_title', sa.String(length=500), nullable=True))
    op.add_column('rss_articles', sa.Column('is_crawled', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_articles', 'is_crawled')
    op.drop_column('rss_articles', 'crawled_title')
    op.drop_column('rss_articles', 'crawled_html')
    op.drop_column('rss_articles', 'crawled_content')
    # ### end Alembic commands ###
